name: flutter_app_tenis
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  rxdart: ^0.22.0
  shared_preferences:
  flutter_svg: ^0.19.3
  http: ^0.13.1
  awesome_dialog: ^1.3.2
  curved_navigation_bar: ^0.3.7
  intl: ^0.17.0
  sticky_headers: "^0.1.8"
  firebase_core: 
  firebase_analytics: 
  cloud_firestore: 
  firebase_storage: 
  image_picker: ^0.7.4
  carousel_slider: ^3.0.0
  firebase_messaging: 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/LoadingImg.gif
    - assets/images/DefaultImg.jpg
  fonts:
    - family: Transat
      fonts:
        - asset: assets/fonts/TransatStandard.otf
          weight: 400
        - asset: assets/fonts/TransatMedium.otf
          weight: 500
        - asset: assets/fonts/TransatBold.otf
          weight: 700
        - asset: assets/fonts/TransatBlack.otf
          weight: 900
