name: flutter_app_tenis
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  rxdart: ^0.22.0
  shared_preferences: 
  flutter_svg: ^0.19.1
  http: ^0.12.2
  awesome_dialog: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/back1.jpg
    - assets/logo.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Light.ttf
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
    - family: Mulish
      fonts:
        - asset: fonts/Mulish-Light.ttf
        - asset: fonts/Mulish-Regular.ttf
        - asset: fonts/Mulish-SemiBold.ttf
        - asset: fonts/Mulish-Bold.ttf

